name: Deploy to GitHub Pages on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages-content

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Get release version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Prepare deployment
        run: |
          mkdir -p build
          if [ -d "gh-pages-content" ]; then
            cp -r gh-pages-content/* build/ || true
          fi
          mkdir -p build/v${{ steps.get_version.outputs.version }}
          cp -r ./ru ./en ./index.html ./build/v${{ steps.get_version.outputs.version }}/
          cp -r ./ru ./en ./index.html ./build/

      - name: Generate versions list
        id: generate_versions
        run: |
          # Создаем список всех версий
          VERSIONS=$(find build -maxdepth 1 -name "v*" -type d | sort -Vr | xargs -I {} basename {})
          echo "versions<<EOF" >> $GITHUB_OUTPUT
          echo "$VERSIONS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update main page with versions
        run: |
          # Создаем HTML для списка версий
          VERSIONS_HTML=""
          for version in ${{ steps.generate_versions.outputs.versions }}; do
            VERSIONS_HTML="${VERSIONS_HTML}<li><a href=\"${version}/\">Версия ${version}</a></li>"
          done

          # Обновляем index.html
          cat > build/index.html << EOF
          <!DOCTYPE html>
          <html lang="ru">
          <head>
              <meta charset="UTF-8">
              <title>Главная страница</title>
          </head>
          <body>
              <h1>Выберите язык / Choose language</h1>
              <ul>
                  <li><a href="ru/">Русский</a></li>
                  <li><a href="en/">English</a></li>
              </ul>
              
              <h2>Доступные версии сайта:</h2>
              <ul>
                  <li><a href="./">Текущая версия (последняя)</a></li>
                  $VERSIONS_HTML
              </ul>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: false
